server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: studentModule
        uri: http://localhost:1010/
        predicates:
        - Path=/student/**
      - id: courseModule
        uri: http://localhost:1011/
        predicates:
        - Path=/course/**
#        filters:
#        - name: Requestsize
#          args:
#            Maxsize: 5000000
