server:
  port: 1011

spring:
  cloud:
    config:
      import-check:
        enabled: false
  config:
    import=optional:configserver:
  application:
    name: course-service
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    properties:
      hibernate:
        dialect: ${datasource.dialect}
        connection:
          characterEncoding: UTF-8
          CharSet: UTF-8
          useUnicode: true
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaulltZone: http://localhost:8083/eureka
